version: '3.1'

services:
    flowise:
        container_name: flowise
        image: flowiseai/flowise
        restart: always
        env_file:
            - ./.env
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        entrypoint: /bin/sh -c "sleep 3; flowise start"

        networks:
            - marvis-network

networks:
  marvis-network:
    external: true
